### ISSUE TITLE
Time in game

### ISSUE THREAD

**Issue by Megaoski** [sergiparrar/BloodBros#15]
### Bug class (A, B, C)

A
### Expected behaviour

Enemy waves should be coming out until you make the win/loose condition
### Actual behaviour

When leaving the game open in godmode for sometime, the enemies stop spawning
### Steps to reproduce that behaviour

Letting the game run in godmode for some time

**Comment by IVREI0T** [comment]
Cannot replicate, most possibly fixed with the new implementation of enemy waves
