### ISSUE TITLE
Crash after playing few times

### ISSUE THREAD

**Issue by d0n3val** [sergiparrar/BloodBros#19]
### Bug class (A, B, C)

A
### Expected behaviour

Not crashing, should loop forever
### Actual behaviour

After 4-6 times playing it crashed moving from the "you win" menu to the initial menu when pressing SPACE
### Steps to reproduce that behaviour

Play 4-6 times in a row without quitting the game

**Comment by IVREI0T** [comment]
Replicate from #17
