### ISSUE TITLE
Explosion Particles Appear when killing the green cowboy enemy.

### ISSUE THREAD

**Issue by rcpauor32** [sergiparrar/BloodBros#6]
### Expected behaviour

A "dying enemy" animation should appear instead of the explosion.
### Actual behaviour

An explosion particle appears (the same as destroying the buildings).
### Steps to reproduce that behaviour

You run the stage and shoot to the green cowboy enemy with the standard weapon.

**Comment by IVREI0T** [comment]
Expected in this build.

We thought it looked cool and we didn't have time to put dying animations ;3c
